include_guard(GLOBAL)
set(_ege_project_root "${CMAKE_CURRENT_LIST_DIR}")
set(EGE_BUILD_DEMO OFF)
set(EGE_BUILD_TEST OFF)
set(EGE_BUILD_TEMP OFF)
if(NOT DEFINED EGE_ENABLE_CAMERA_CAPTURE)
    set(EGE_ENABLE_CAMERA_CAPTURE ON)
endif()
if(TARGET xege)
    message(FATAL_ERROR "EGE requires the target name 'xege'. Rename the existing target before adding EGE.")
endif()
add_subdirectory("${_ege_project_root}/ege" "${CMAKE_BINARY_DIR}/ege")

# Attach EGE to existing executable targets when converting a CMake project.
function(_ege_attach_targets directory)
    get_property(_targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(_target IN LISTS _targets)
        get_target_property(_type ${_target} TYPE)
        if(_type STREQUAL "EXECUTABLE")
            # Direct property append supports both existing plain and keyword link signatures.
            set_property(TARGET ${_target} APPEND PROPERTY LINK_LIBRARIES xege)
            string(SHA256 _asset_id "${_ege_project_root}:${_target}")
            set(_asset_target "_xege_assets_${_asset_id}")
            target_compile_features(${_target} PRIVATE cxx_std_17)
            target_include_directories(${_target} PRIVATE "${_ege_project_root}")
            if(MSVC)
                target_compile_options(${_target} PRIVATE /utf-8)
            endif()
            foreach(_image getimage.png getimage.jpg)
                configure_file("${_ege_project_root}/${_image}" "${CMAKE_BINARY_DIR}/${_image}" COPYONLY)
            endforeach()
            # Generated script avoids a target-location dependency cycle on older CMake.
            file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/ege-assets-${_asset_id}-$<CONFIG>.cmake"
                CONTENT "file(MAKE_DIRECTORY \"$<TARGET_FILE_DIR:${_target}>\")\nfile(COPY \"${_ege_project_root}/getimage.png\" \"${_ege_project_root}/getimage.jpg\" DESTINATION \"$<TARGET_FILE_DIR:${_target}>\")\n")
            add_custom_target(${_asset_target}
                COMMAND ${CMAKE_COMMAND} -P "${CMAKE_CURRENT_BINARY_DIR}/ege-assets-${_asset_id}-$<CONFIG>.cmake")
            add_dependencies(${_target} ${_asset_target})
            if(APPLE)
                target_link_options(${_target} PRIVATE
                    "LINKER:-sectcreate,__TEXT,__info_plist,${_ege_project_root}/macos-camera-info.plist")
            endif()
        endif()
    endforeach()
    get_property(_directories DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(_directory IN LISTS _directories)
        if(NOT _directory STREQUAL "${_ege_project_root}/ege")
            _ege_attach_targets("${_directory}")
        endif()
    endforeach()
endfunction()
_ege_attach_targets("${CMAKE_CURRENT_SOURCE_DIR}")
