ege.repository=https://github.com/x-ege/xege
ege.commit=09387a806e3d8cafde84bf0bd91b775d681b27ac
ccap.repository=https://github.com/wysaid/CameraCapture
ccap.commit=d1876005be7e7cc0c370fadd05dbac6c658c4a17
