name: CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'  # 避免 tag push 触发这个 workflow
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Verify plugin
        run: ./gradlew verifyPlugin

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: plugin-artifact
          path: build/distributions/*.zip
          retention-days: 7
